"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 当前工程的根目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 密钥，后期如果需要加密时，可以使用此密钥
SECRET_KEY = '1l)42j*fs&e!1@d)^0uzhev2)@!&q4z04nj9nc@-vu$zg=*ips'

# 调试模式,默认开启
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许哪些域名可以访问django
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # 将数据储存在数据库中
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'person.apps.PersonConfig',
]

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 如需禁用session，将上图中的session中间件注释掉即可
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # CSRF防护验证,CSRF防护机制
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 通过HttpResponse对象中的set_cookie方法来设置cookie
# HttpResponse.set_cookie(cookie名, value=cookie值, max_age=cookie有效期)

# 设置session数据的储存方式，储存在数据库中
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# 储存在本机内存中,比数据库的方式读写更快，如果丢失则不能找回
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# 混合存储，优先从本机内存中存取，如果没有则从数据库中存取
# SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 工程路由入口文件
ROOT_URLCONF = 'demo.urls'

# 模板配置项
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'BACKEND': 'django.template.backends.jinja2.jinja2',  # 修改
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 此处修改
        'APP_DIRS': True,
        'OPTIONS': {
            # 'environment': 'jinja2_env.environment',# 修改2
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 上线后/生产环境的启动文件
WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# 数据库配置
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',  # 数据库主机
        'PORT': 3306,  # 数据库端口
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'mysql',  # 数据库用户密码
        'NAME': 'django_demo'  # 数据库名字
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

# 密码认证
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# 语言
# LANGUAGE_CODE = 'en-us'

LANGUAGE_CODE = 'zh-hans'  # 使用中国语言

# 时区
# TIME_ZONE = 'UTC'

TIME_ZONE = 'Asia/Shanghai'  # 使用中国上海的时间

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# 静态文件访问的路由前缀（可修改）
# static files (css, JavaScript, Images)
# 静态文件访问路由前缀
STATIC_URL = '/static/'
# 指定静态文件加载目录
STATICFILES_DIRS =[
    os.path.join(BASE_DIR, 'static_files'),
    # os.path.join(BASE_DIR, 'static_files/see_png'),

]
